-- Create DayEntry table
CREATE TABLE IF NOT EXISTS day_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    total_worked_minutes INTEGER NOT NULL,
    overtime_minutes INTEGER NOT NULL,
    average_worked_minutes INTEGER NOT NULL
);

-- Create TimeEntry table
CREATE TABLE IF NOT EXISTS time_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_entry_id BIGINT NOT NULL,
    time TIME NOT NULL,
    FOREIGN KEY (day_entry_id) REFERENCES day_entries(id)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_day_entries_date ON day_entries(date);
CREATE INDEX IF NOT EXISTS idx_time_entries_day_entry_id ON time_entries(day_entry_id);
